# docker-compose.yml

services:
  all-in-one:
    build:
      context: .
      dockerfile: Dockerfile
    image: mlowls_all_in_one:latest
    pull_policy: never
    ports:
      - "8000:8000"   # FastAPI
      - "8080:8080"   # Label Studio
      - "5000:5000"   # MLflow
    volumes:
      - label-studio-data:/label-studio/data
      - mlflow-data:/mlflow
    restart: unless-stopped

volumes:
  label-studio-data:
  mlflow-data: