# ml_owls_config.yaml
app:
  name: "BirdCLEF Inference API"
  host: "0.0.0.0"
  port: 8000

model:
  path: "models/bird_model.onnx"

labelstudio:
  url: "http://labelstudio:8080/api/projects/1/import"
