# ml_owls_config.yaml
app:
  name: "BirdCLEF Inference API"
  host: "0.0.0.0"
  port: 8000

model:
  metadata_path: "models/birdclef_best.json"
  config_path: "configs/model/model_config.yaml"
  top_k: 5
  confidence_threshold: 0.1
  use_gpu: false

labelstudio:
#  url: "http://labelstudio:8080/api/projects/1/import"
  url: "http://labelstudio"
  port: "8080"